stages:
  - publish-to-registry
  - deploy

variables:
  VARIABLE_DATA: Gitlab-CI-YAML

publish-to-registry:
  stage: publish-to-registry
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

deploy:
  image: 
    name: dtzar/helm-kubectl
    entrypoint: [""]
  stage: deploy
  services:
    - docker:dind
  environment:
    name: production
  before_script:
    - apk add moreutils

    - |
      for filename in kubernetes/*.yaml; do
          envsubst < "$filename" | sponge "$filename"
      done

    - kubectl config use-context andrebrito16/scaleways
  script:
    - kubectl apply -f kubernetes
  only:
    - master