#@data/values
---
postgres:
  enabled: true
  values:
    primary:
      nodeSelector:
        - name: kubernetes.io/arch
          value: amd64
      persistence:
        enabled: true
        size: 1Gi